pipeline{
    // agent{
    //     label "node"
    // }
    agent any

    parameters {

        string(defaultValue: "project-1", description: 'Confirm project name', name: 'InputProjectName')

        choice(
            choices: [
                'EU-WEST-2A',
                'EU-WEST-2B',
                'EU-WEST-2C'
            ], 
            description: 'What AWS region?', 
            name: 'SelectRegion'
        )

        booleanParam(defaultValue: false, description: 'CONFRM DEPLOYMENT?', name: 'ConfirmDeployment')


    }

    stages{
        stage("User Input Configurations"){
            steps{
                echo "========START User Input Configurations========"
                echo "Project Name is: ${params.InputProjectName} \n"
                echo "Selected Region is: ${params.SelectRegion} \n"
                echo "Start deployment: ${params.ConfirmDeployment} \n"
            }
            post{
                // always{
                //     echo "========always========"
                // }
                success{
                    echo "========SUCCESS======== User Input Configurations========"
                }
                failure{
                    echo "========FAILED======== User Input Configurations========"
                }
            }
        }
    }
    post{
        // always{
        //     echo "========always========"
        // }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}