pipeline {
    agent any

    // parameters {
    //     booleanParam(defaultValue: false, description: "Enable service?", name: "myBoolean")
    // }

    parameters {
        booleanParam(
            defaultValue: false,
            description: "Select ON or OFF",
            name: BoolSellect
        )
    }

    stages {
        stage("Demo"){
            steps {
                echo "booleanParam is set to: ${params.BoolSellect}"
            }
        }
    }
}